# Generated by Django 4.2.1 on 2023-05-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_products_spu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='brand',
            new_name='override_brand',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='title',
            new_name='override_title',
        ),
    ]
